frase = input ('Digite algo: ')
print('O tipo primitivo desse valor é',type (frase))
print('So tem espaços?' ,frase.isspace())
print('É um número?',frase.isnumeric())
print('É alfabético?',frase.isalpha())
print('É alfanúmerico?',frase.isalnum())
print('Está em maiscúlas?',frase.isupper())
print('Está em minúsculas?',frase.islower())
print('Está capitalizada {}'.format(frase.istitle()))