nome = str(input('Digite o seu nome completo: ')).strip()
print('Analisando o seu nome...')
print('Seu nome em maiscúlo é {}'.format(nome.upper()))
print('Seu nome em minuscúlo é {}'.format(nome.lower()))
print('Seu nome tem ao todo tem {} letras'.format(len(nome) - nome.count(' ')))
divide = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras'.format(divide[0],nome.find(' ')))
#print('Seu primeiro nome é {} e ele tem {} letras'.format(divide[0],len(divide[0])))
